#!/bin/bash

if [ -z "$@" ]; then
        if [ "$USER" == "root" ]; then 
                "/usr/local/lib/p7zip/7zFM" "/root" 
        else
                "/usr/local/lib/p7zip/7zFM" "/home/$USER"
        fi
else
        "/usr/local/lib/p7zip/7zFM" "$@"
fi
